#! /bin/bash

# loginuser
echo "Create a user with the same name as your linux login:"
sudo createuser -s -U postgres

echo "Creating tidsur user"
psql -d postgres -U postgres < create_user.sql

echo "Creating tidsur db with tables" 
psql -d postgres -U groceries < create_database.sql
psql -d groceries -U groceries < create_tables.sql

echo "Done!"
