#! /bin/bash

# loginuser
echo "Creating clocking user"
psql < create_user.sql

echo "Creating clocking db with tables" 
psql -d postgres -U clocking < create_database.sql
psql -d clocking -U clocking < create_tables.sql

echo "Done!"
