#! /bin/bash

echo "Deleting db and user, creating tidsur user"
cat drop_db_and_user.sql create_user.sql | psql -d postgres -U postgres

echo "Creating tidsur db with tables" 
psql -d postgres -U tidsur < create_database.sql
psql -d tidsur -U tidsur < create_tables.sql

echo "Done!"
