#! /bin/bash

echo "Deleting db and user, creating clocking user"
cat drop_db_and_user.sql create_user.sql | psql

echo "Creating clocking db with tables" 
psql -d postgres -U clocking < create_database.sql
psql -d clocking -U clocking < create_tables.sql

echo "Done!"
